<?php
/**
 * Language labels for extension 'pil_mailform'
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'pi1_title' => 'TMailform',
		'pi1_plus_wiz_description' => 'Adds a template based mailform',
		'pil_mailform' => 'TMailform',
		'fsheet.sDEF' => 'General settings',
		'ffield.testmode' => 'Testmode ',
		'ffield.staticSubject' => 'Static subject ',
		'ffield.overrideSubject' => 'Subject user override ',
		'ffield.typeofRecipient' => 'Use recipient ',
		'ffield.userSubjectPrefix' => 'User subject prefix ',
		'ffield.typeofRecipient.0' => ' Static recipient(s)',
		'ffield.typeofRecipient.1' => ' Dynamic recipient',
		'ffield.staticRecipient' => 'Static recipient(s) ',
		'ffield.dynamicRecipient' => 'Dynamic recipient ',
		'ffield.copyToUser' => 'Copy to user ',
		'ffield.copyToUser.0' => 'No ',
		'ffield.copyToUser.1' => 'Yes ',
		'ffield.copyToUser.2' => 'User select ',
		'ffield.userCopySubject' => 'User copy subject ',
		'ffield.template' => 'Template ',
		'ffield.useLL' => 'Multiple language support',
		'ffield.LLFile' => 'locallang file',
		'fsheet.sVALIDATION' => 'Field settings',
		'ffield.errorSubstitution' => 'Replace error markers with ',
		'ffield.requiredValues' => 'Required values',
		'ffield.defaultValues' => 'Default values',
        'ffield.storeValues' => 'Store values',
        'ffield.dateMarker' => 'Marker _DATE format',
        'ffield.timeMarker' => 'Marker _TIME format',
		'fsheet.sHEADERS' => 'Mail headers',
		'ffield.fromName' => '"From" name ',
		'ffield.fromMail' => '"From" email ',
		'ffield.overrideFromHeader' => '"From" header user override ',
		'ffield.replyToName' => '"Reply-To" name ',
		'ffield.replyToMail' => '"Reply-To" email ',
		'ffield.overrideReplyToHeader' => '"Reply-To" header user override ',
		'ffield.overrideHeaderNameFormat' => 'Header name override format',
		'ffield.overrideHeaderNameFormat.0' => ' "name surname"',
		'ffield.overrideHeaderNameFormat.1' => ' "surname, name"',
		'ffield.discloseRecipient' => 'Disclose recipient email in user copy',
		'ffield.Cc' => '"Cc" addresses ',
		'ffield.Bcc' => '"Bcc" addresses ',
		'ffield.contentTransferEncoding' => '"Content-Transfer-Encoding" ',
		'ffield.contentTransferEncoding.0' => '8bit',
		'ffield.contentTransferEncoding.1' => '7bit',
		'ffield.contentTransferEncoding.2' => 'base64',
		'ffield.contentTransferEncoding.3' => 'binary',
		'ffield.contentTransferEncoding.4' => 'quoted-printable',
		'ffield.contentType' => '"Content-Type" ',
		'ffield.contentType.0' => 'text/plain',
		'ffield.contentType.1' => 'text/html',
		'ffield.charset' => 'Charset ',
		'fsheet.sSMTP' => 'SMTP settings',
		'ffield.useMailer' => 'Send mail using ',
		'ffield.useMailer.0' => 'PHP mail()',
		'ffield.useMailer.1' => 'sendmail',
		'ffield.useMailer.2' => 'smtp',
		'ffield.useMailer.-1' => 'Disable mail (only store values)',
		'ffield.sendmailPath' => 'Path to sendmail ',
		'ffield.smtpHost' => 'SMTP host ',
		'ffield.smtpPort' => 'SMTP port ',
		'ffield.smtpAuth' => 'Use SMTP authentication ',
		'ffield.smtpUser' => 'SMTP username ',
		'ffield.smtpPasswd' => 'SMTP Password ',
	),
	'dk' => Array (
		'pi1_title' => 'TMailform',
		'pi1_plus_wiz_description' => 'Tilfшjer en skabelonbaseret mailformular',
		'pil_mailform' => 'TMailform',
		'fsheet.sDEF' => 'Generelle indstillinger',
		'ffield.testmode' => 'Testmode ',
		'ffield.staticSubject' => 'Statisk emne ',
		'ffield.overrideSubject' => 'Bruger emne ',
		'ffield.typeofRecipient' => 'Benyt modtager ',
		'ffield.userSubjectPrefix' => 'Bruger emne prefix ',
		'ffield.typeofRecipient.0' => ' Statisk(e) modtager(e)',
		'ffield.typeofRecipient.1' => ' Dynamisk modtager',
		'ffield.staticRecipient' => 'Statisk(e) modtager(e) ',
		'ffield.dynamicRecipient' => 'Dynamisk modtager ',
		'ffield.copyToUser' => 'Kopi til bruger ',
		'ffield.copyToUser.0' => 'Nej ',
		'ffield.copyToUser.1' => 'Ja ',
		'ffield.copyToUser.2' => 'Vжlges af bruger ',
		'ffield.userCopySubject' => 'Bruger kopi emne ',
		'ffield.template' => 'Skabelon ',
		'ffield.useLL' => 'Support for flere sprog',
		'ffield.LLFile' => 'locallang fil',
		'fsheet.sVALIDATION' => 'Feltindstillinger',
		'ffield.errorSubstitution' => 'Erstat fejl-markшrer med ',
		'ffield.requiredValues' => 'Nшdvendige vжrdier',
		'ffield.defaultValues' => 'Forvalgte vжrdier',
        'ffield.storeValues' => 'Gem vжrdier',
        'ffield.dateMarker' => 'Markшr _DATE format',
        'ffield.timeMarker' => 'Markшr _TIME format',
		'fsheet.sHEADERS' => 'Mail headers',
		'ffield.fromName' => '"From" navn ',
		'ffield.fromMail' => '"From" email ',
		'ffield.overrideFromHeader' => '"From" header fra bruger ',
		'ffield.replyToName' => '"Reply-To" navn ',
		'ffield.replyToMail' => '"Reply-To" email ',
		'ffield.overrideReplyToHeader' => '"Reply-To" header fra bruger ',
		'ffield.overrideHeaderNameFormat' => 'Header navn fra bruger format',
		'ffield.overrideHeaderNameFormat.0' => ' "fornavn efternavn"',
		'ffield.overrideHeaderNameFormat.1' => ' "efternavn, fornavn"',
		'ffield.discloseRecipient' => 'Brug modtager email som afsender i brugerkopi',
		'ffield.Cc' => '"Cc" adresser ',
		'ffield.Bcc' => '"Bcc" adresser ',
		'ffield.contentTransferEncoding' => '"Content-Transfer-Encoding" ',
		'ffield.contentTransferEncoding.0' => '8bit',
		'ffield.contentTransferEncoding.1' => '7bit',
		'ffield.contentTransferEncoding.2' => 'base64',
		'ffield.contentTransferEncoding.3' => 'binary',
		'ffield.contentTransferEncoding.4' => 'quoted-printable',
		'ffield.contentType' => '"Content-Type" ',
		'ffield.contentType.0' => 'text/plain',
		'ffield.contentType.1' => 'text/html',
		'ffield.charset' => 'Charset ',
		'fsheet.sSMTP' => 'SMTP indstillinger',
		'ffield.useMailer' => 'Send mail ved hjжlp af ',
		'ffield.useMailer.0' => 'PHP mail()',
		'ffield.useMailer.1' => 'sendmail',
		'ffield.useMailer.2' => 'smtp',
		'ffield.useMailer.-1' => 'Send ikke mail (Gem kun vжdier)',
		'ffield.sendmailPath' => 'Sti til sendmail ',
		'ffield.smtpHost' => 'SMTP host ',
		'ffield.smtpPort' => 'SMTP port ',
		'ffield.smtpAuth' => 'Benyt SMTP godkendelse ',
		'ffield.smtpUser' => 'SMTP brugernavn ',
		'ffield.smtpPasswd' => 'SMTP adgangskode ',
	),
	'de' => Array (
		'pi1_title' => 'TMailform',
		'pi1_plus_wiz_description' => 'Fьgt ein template-basiertes Mailformular hinzu.',
		'pil_mailform' => 'TMailform',
		'fsheet.sDEF' => 'Allgemeine Einstellungen',
		'ffield.testmode' => 'Testmodus ',
		'ffield.staticSubject' => 'Betreff (fix) ',
		'ffield.overrideSubject' => 'Betreff durch User ьberschreiben ',
		'ffield.typeofRecipient' => 'Empfдngertyp ',
		'ffield.userSubjectPrefix' => 'Prдfix fьr User-Betreff ',
		'ffield.typeofRecipient.0' => ' Fixe(r) Empfдnger',
		'ffield.typeofRecipient.1' => ' Dynamische(r) Empfдnger',
		'ffield.staticRecipient' => 'Fixe(r) Empfдnger ',
		'ffield.dynamicRecipient' => 'Dynamische(r) Empfдnger ',
		'ffield.copyToUser' => 'Kopie an User ',
		'ffield.copyToUser.0' => 'Nein ',
		'ffield.copyToUser.1' => 'Ja ',
		'ffield.copyToUser.2' => 'Userauswahl ',
		'ffield.userCopySubject' => 'Betreff der Kopie ',
		'ffield.template' => 'Template ',
		'ffield.useLL' => 'Multiple language support',
		'ffield.LLFile' => 'locallang file',		
		'fsheet.sVALIDATION' => 'Feldeinstellungen',	// Feldeinstellungen
		'ffield.requiredFields' => 'Pflichtfelder ',
		'ffield.errorSubstitution' => 'Ersetze Fehlermarker mit ',
		'ffield.defaultValues' => '',
        'ffield.storeValues' => 'Store values',
        'ffield.dateMarker' => 'Marker _DATE format',
        'ffield.timeMarker' => 'Marker _TIME format',
		'fsheet.sHEADERS' => 'Mailheader',
		'ffield.fromName' => '"From"-Name ("Von")',
		'ffield.fromMail' => '"From"-E-Mail ("Von")',
		'ffield.overrideFromHeader' => '"From" durch User ьberschreiben ',
		'ffield.replyToName' => '"Reply-To"-Name  ',
		'ffield.replyToMail' => '"Reply-To"-E-Mail ',
		'ffield.overrideReplyToHeader' => '"Reply-To" durch User ьberschreiben ',
		'ffield.overrideHeaderNameFormat' => 'Header name override format',
		'ffield.overrideHeaderNameFormat.0' => ' "name surname"',
		'ffield.overrideHeaderNameFormat.1' => ' "surname, name"',
		'ffield.discloseRecipient' => 'Disclose recipient email in user copy',
		'ffield.Cc' => '"Cc"-Adressen ',
		'ffield.Bcc' => '"Bcc"-Adressen ',
		'ffield.contentTransferEncoding' => '"Content-Transfer-Encoding" (Kodierung)',
		'ffield.contentTransferEncoding.0' => '8bit',
		'ffield.contentTransferEncoding.1' => '7bit',
		'ffield.contentTransferEncoding.2' => 'base64',
		'ffield.contentTransferEncoding.3' => 'binary',
		'ffield.contentTransferEncoding.4' => 'quoted-printable',
		'ffield.contentType' => '"Content-Type" (Format) ',
		'ffield.contentType.0' => 'text/plain (nur Text)',
		'ffield.contentType.1' => 'text/html (HTML)',
		'ffield.charset' => 'Charset (Zeichensatz) ',
		'fsheet.sSMTP' => 'SMTP-Einstellungen',
		'ffield.useMailer' => 'Sende E-Mail durch ',
		'ffield.useMailer.0' => 'PHP-Funktion mail()',
		'ffield.useMailer.1' => 'sendmail-Programm',
		'ffield.useMailer.2' => 'SMTP-Server',
		'ffield.useMailer.-1' => 'Disable mail (only store values)',
		'ffield.sendmailPath' => 'Pfad zu sendmail ',
		'ffield.smtpHost' => 'SMTP-Host ',
		'ffield.smtpPort' => 'SMTP-Port ',
		'ffield.smtpAuth' => 'Verwende SMTP-Authentifizierung ',
		'ffield.smtpUser' => 'SMTP-Username ',
		'ffield.smtpPasswd' => 'SMTP-Passwort ',
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
	),
	'es' => Array (
	),
	'nl' => Array (
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
		'pi1_title' => 'TMailform',
		'pi1_plus_wiz_description' => 'Добавить форму отправки почты (основана на шаблонах)',
		'pil_mailform' => 'TMailform',
		'fsheet.sDEF' => 'Основные настройки',
		'ffield.testmode' => 'Режим тестирования ',
		'ffield.staticSubject' => 'Статическая тема ',
		'ffield.overrideSubject' => 'Тема переопределяется пользователем ',
		'ffield.typeofRecipient' => 'Использовать получателя ',
		'ffield.userSubjectPrefix' => 'Префикс темы пользователя ',
		'ffield.typeofRecipient.0' => ' Статические получатель(и)',
		'ffield.typeofRecipient.1' => ' Динамические получатель(и)',
		'ffield.staticRecipient' => 'Статические получатель(и) ',
		'ffield.dynamicRecipient' => 'Динамические получатель(и) ',
		'ffield.copyToUser' => 'Копия пользователю ',
		'ffield.copyToUser.0' => 'Нет ',
		'ffield.copyToUser.1' => 'Да ',
		'ffield.copyToUser.2' => 'Выбор пользователя ',
		'ffield.userCopySubject' => 'Тема копии пользователя ',
		'ffield.template' => 'Шаблон ',
		'ffield.useLL' => 'Multiple language support',
		'ffield.LLFile' => 'locallang file',
		'fsheet.sVALIDATION' => 'Проверка полей',
		'ffield.errorSubstitution' => 'Заменить маркеры ошибок этим ',
        'ffield.requiredValues' => 'Required values',
        'ffield.defaultValues' => 'Default values',
        'ffield.storeValues' => 'Store values',
        'ffield.dateMarker' => 'Marker _DATE format',
        'ffield.timeMarker' => 'Marker _TIME format',
		'fsheet.sHEADERS' => 'Почтовые заголовки',
		'ffield.fromName' => '"From" имя ',
		'ffield.fromMail' => '"From" email ',
		'ffield.overrideFromHeader' => '"From" переопределенный пользователем заголовок ',
		'ffield.replyToName' => '"Reply-To" имя ',
		'ffield.replyToMail' => '"Reply-To" email ',
		'ffield.overrideReplyToHeader' => '"Reply-To" переопределенный пользователем заголовок ',
		'ffield.overrideHeaderNameFormat' => 'Header name override format',
		'ffield.overrideHeaderNameFormat.0' => ' "name surname"',
		'ffield.overrideHeaderNameFormat.1' => ' "surname, name"',
		'ffield.discloseRecipient' => 'Disclose recipient email in user copy',
		'ffield.Cc' => '"Cc" адреса ',
		'ffield.Bcc' => '"Bcc" адреса ',
		'ffield.contentTransferEncoding' => '"Content-Transfer-Encoding" ',
		'ffield.contentTransferEncoding.0' => '8bit',
		'ffield.contentTransferEncoding.1' => '7bit',
		'ffield.contentTransferEncoding.2' => 'base64',
		'ffield.contentTransferEncoding.3' => 'binary',
		'ffield.contentTransferEncoding.4' => 'quoted-printable',
		'ffield.contentType' => '"Content-Type" ',
		'ffield.contentType.0' => 'text/plain',
		'ffield.contentType.1' => 'text/html',
		'ffield.charset' => 'Charset ',
		'fsheet.sSMTP' => 'Настройки SMTP',
		'ffield.useMailer' => 'Способ отправки почты ',
		'ffield.useMailer.0' => 'PHP mail()',
		'ffield.useMailer.1' => 'sendmail',
		'ffield.useMailer.2' => 'smtp',
		'ffield.useMailer.-1' => 'Disable mail (only store values)',
		'ffield.sendmailPath' => 'Путь к sendmail ',
		'ffield.smtpHost' => 'SMTP хост ',
		'ffield.smtpPort' => 'SMTP порт ',
		'ffield.smtpAuth' => 'Использовать SMTP аутентификацию ',
		'ffield.smtpUser' => 'SMTP username ',
		'ffield.smtpPasswd' => 'SMTP Password ',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>