<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-02-26 21:39

$extensionPath = t3lib_extMgm::extPath('transactor_paymill');
return array(
	'tx_transactorpaymill_control' => $extensionPath . 'control/class.tx_transactorpaymill_control.php',
	'tx_transactorpaymill_gateway' => $extensionPath . 'model/class.tx_transactorpaymill_gateway.php',
);
?>