<?php
return array(
	'BE' => array(
		'disable_exec_function' => '0',
		'installToolPassword' => '$P$CDN1hbg/p4vBX072OeRdg2WIirKRlK/',
		'loginSecurityLevel' => 'normal',
		'versionNumberInFilename' => '0',
		'warning_email_addr' => 'aljosa.borstnar@gmail.com',
	),
	'DB' => array(
		'database' => 'zisha',
		'extTablesDefinitionScript' => 'extTables.php',
		'host' => '127.0.0.1',
		'password' => '',
		'port' => 3306,
		'username' => 'root',
	),
	'EXT' => array(
		'extConf' => array(
			'css_select' => 'a:3:{s:6:"CSSDIR";s:23:"fileadmin/template/css/";s:6:"CSSEXT";s:3:"css";s:12:"ALLOWSUBDIRS";s:1:"1";}',
			'em' => 'a:1:{s:17:"selectedLanguages";s:2:"sl";}',
			'imagecycle' => 'a:5:{s:7:"effects";s:233:",none,blindX,blindY,blindZ,cover,curtainX,curtainY,fade,fadeout,fadeZoom,growX,growY,scrollUp,scrollDown,scrollLeft,scrollRight,scrollHorz,scrollVert,shuffle,slideX,slideY,toss,turnUp,turnDown,turnLeft,turnRight,uncover,wipe,zoom,all";s:11:"effectsCoin";s:27:",random,swirl,rain,straight";s:11:"effectsNivo";s:178:",random,sliceDown,sliceDownLeft,sliceUp,sliceUpLeft,sliceUpDown,sliceUpDownLeft,fold,fade,slideInRight,slideInLeft,boxRandom,boxRain,boxRainReverse,boxRainGrow,boxRainGrowReverse";s:15:"nivoThemeFolder";s:34:"EXT:imagecycle/res/css/nivoslider/";s:24:"useSelectInsteadCheckbox";s:1:"0";}',
			'indexed_search' => 'a:17:{s:8:"pdftools";s:9:"/usr/bin/";s:8:"pdf_mode";s:2:"20";s:5:"unzip";s:9:"/usr/bin/";s:6:"catdoc";s:9:"/usr/bin/";s:6:"xlhtml";s:9:"/usr/bin/";s:7:"ppthtml";s:9:"/usr/bin/";s:5:"unrtf";s:9:"/usr/bin/";s:9:"debugMode";s:1:"0";s:18:"fullTextDataLength";s:1:"0";s:23:"disableFrontendIndexing";s:1:"0";s:6:"minAge";s:2:"24";s:6:"maxAge";s:1:"0";s:16:"maxExternalFiles";s:1:"5";s:26:"useCrawlerForExternalFiles";s:1:"0";s:11:"flagBitMask";s:3:"192";s:16:"ignoreExtensions";s:0:"";s:17:"indexExternalURLs";s:1:"0";}',
			'ke_dompdf' => 'a:0:{}',
			'pil_mailform' => 'a:1:{s:3:"db.";a:2:{s:5:"mode.";a:4:{s:3:"get";s:1:"0";s:3:"new";s:1:"0";s:3:"add";s:1:"0";s:6:"update";s:1:"0";}s:6:"tables";s:0:"";}}',
			'realurl' => 'a:5:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
			'rgmediaimages' => 'a:1:{s:6:"rename";s:1:"1";}',
			'rlmp_tmplselector' => 'a:1:{s:12:"templateMode";s:4:"file";}',
			'rtehtmlarea' => 'a:8:{s:21:"noSpellCheckLanguages";s:23:"ja,km,ko,lo,th,zh,b5,gb";s:15:"AspellDirectory";s:15:"/usr/bin/aspell";s:20:"defaultConfiguration";s:105:"Typical (Most commonly used features are enabled. Select this option if you are unsure which one to use.)";s:12:"enableImages";s:1:"1";s:20:"enableInlineElements";s:1:"0";s:19:"allowStyleAttribute";s:1:"1";s:24:"enableAccessibilityIcons";s:1:"0";s:16:"forceCommandMode";s:1:"0";}',
			'rzcolorbox' => 'a:1:{s:9:"allowHtml";s:1:"0";}',
			'saltedpasswords' => 'a:2:{s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}s:3:"FE.";a:5:{s:7:"enabled";i:0;s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}}',
			'seo_basics' => 'a:2:{s:10:"xmlSitemap";s:1:"1";s:16:"sourceFormatting";s:1:"1";}',
			'simulatestatic' => 'a:0:{}',
			't3jquery' => 'a:11:{s:15:"alwaysIntegrate";s:1:"1";s:17:"integrateToFooter";s:1:"0";s:18:"dontIntegrateOnUID";s:1:"1";s:23:"dontIntegrateInRootline";s:0:"";s:13:"jqLibFilename";s:23:"jquery-###VERSION###.js";s:9:"configDir";s:19:"uploads/tx_t3jquery";s:13:"jQueryVersion";s:5:"1.3.x";s:15:"jQueryUiVersion";s:5:"1.8.x";s:18:"jQueryTOOLSVersion";s:0:"";s:16:"integrateFromCDN";s:1:"0";s:11:"locationCDN";s:6:"google";}',
			'transactor_paymill' => 'a:4:{s:10:"privatekey";s:32:"a5bb9cd2a13ee35d536b79a309a070cc";s:9:"publickey";s:32:"463412031171a07ce76a922cd82ec805";s:11:"provideruri";s:27:"https://api.paymill.com/v2/";s:8:"testMode";s:1:"1";}',
			'tt_news' => 'a:20:{s:13:"useStoragePid";s:1:"1";s:17:"requireCategories";s:1:"0";s:18:"useInternalCaching";s:1:"1";s:11:"cachingMode";s:6:"normal";s:13:"cacheLifetime";s:1:"0";s:13:"cachingEngine";s:8:"internal";s:11:"treeOrderBy";s:3:"uid";s:13:"prependAtCopy";s:1:"1";s:5:"label";s:5:"title";s:9:"label_alt";s:0:"";s:10:"label_alt2";s:0:"";s:15:"label_alt_force";s:1:"0";s:21:"categorySelectedWidth";s:1:"0";s:17:"categoryTreeWidth";s:1:"0";s:25:"l10n_mode_prefixLangTitle";s:1:"1";s:22:"l10n_mode_imageExclude";s:1:"1";s:20:"hideNewLocalizations";s:1:"0";s:24:"writeCachingInfoToDevlog";s:10:"disabled|0";s:23:"writeParseTimesToDevlog";s:1:"0";s:18:"parsetimeThreshold";s:3:"0.1";}',
		),
	),
	'FE' => array(
		'pageNotFound_handling' => '404',
	),
	'GFX' => array(
		'gdlib_png' => '1',
		'im' => '1',
		'im_path' => '/usr/bin/',
		'im_path_lzw' => '',
		'imagefile_ext' => 'gif,jpg,jpeg,tif,tiff,bmp,pcx,tga,png,pdf,ai',
		'thumbnails' => '1',
	),
	'INSTALL' => array(
		'wizardDone' => array(
			'TYPO3\CMS\Install\CoreUpdates\InstallSysExtsUpdate' => '["info","perm","func","filelist","about","cshmanual","feedit","opendocs","recycler","t3editor","reports","scheduler","simulatestatic"]',
			'TYPO3\CMS\Install\Updates\FileIdentifierHashUpdate' => 1,
			'TYPO3\CMS\Install\Updates\FilemountUpdateWizard' => 1,
			'TYPO3\CMS\Install\Updates\TceformsUpdateWizard' => 'tt_content:image,pages:media,pages_language_overlay:media',
			'TYPO3\CMS\Install\Updates\TruncateSysFileProcessedFileTable' => 1,
			'tx_coreupdates_installnewsysexts' => '1',
		),
	),
	'MAIL' => array(
		'transport' => 'mail',
		'transport_smtp_encrypt' => '',
		'transport_smtp_password' => '25c4c726-6fb2-4cc2-8b53-b2499d1ba78f',
		'transport_smtp_server' => 'smtp.mandrillapp.com:587',
		'transport_smtp_username' => 'naprej',
	),
	'SYS' => array(
		'compat_version' => '6.2',
		'debugExceptionHandler' => '',
		'devIPmask' => '',
		'displayErrors' => '0',
		'enableDeprecationLog' => '0',
		'enable_errorDLOG' => '0',
		'enable_exceptionDLOG' => '0',
		'encryptionKey' => 'b2287268c5b52ae3d4d19e1987a77b18ae67d50fbaf6d1e3d77d31cb55435951ffab58a1455894144fccb5dbb01784dc',
		'errorHandler' => '',
		'productionExceptionHandler' => '',
		'sitename' => 'Zisha',
		'systemLog' => '',
	),
);
?>